### ISSUE TITLE
A busca de animais para adoção pode ser filtrada pelo tipo, sexo, idade, porte, pelagem e saúde do animal.

### ISSUE THREAD

**Issue by andressajob** [lab-ds/trabalho2-chaos-team#3]

**Comment by andressajob** [comment]
Idade: se é filhote ou adulto.
Porte: pequeno, médio ou grande.
Pelagem: curta ou longa.
Saúde: vacinado, castrado ou vermifugado.

**Comment by rodrigonoll** [comment]
a localização tb é bem importante

**Comment by andressajob** [comment]
Commit do teste 4f47adc9b77fdbb964fd3625ff815e21fcf91150.
